//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Console
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Console()
        {
            this.ConsoleGames = new HashSet<ConsoleGame>();
        }
    
        public string consoleID { get; set; }
        public string consoleName { get; set; }
        public string consoleVersion { get; set; }
        public string predecessor { get; set; }
        public string successor { get; set; }
        public Nullable<decimal> price { get; set; }
        public string info { get; set; }
        public string top3Titles { get; set; }
        public Nullable<int> gameID { get; set; }
        public Nullable<int> companyID { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsoleGame> ConsoleGames { get; set; }
    }
}
