//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GamingEntities : DbContext
    {
        public GamingEntities()
            : base("name=GamingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoardGame> BoardGames { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Console> Consoles { get; set; }
        public virtual DbSet<ConsoleGame> ConsoleGames { get; set; }
        public virtual DbSet<ConsoleGameDeveloper> ConsoleGameDevelopers { get; set; }
        public virtual DbSet<DandDProfile> DandDProfiles { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GamertagRegister> GamertagRegisters { get; set; }
    }
}
