//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardGame
    {
        public int boardGameID { get; set; }
        public string title { get; set; }
        public Nullable<int> forAges { get; set; }
        public string typeOfGame { get; set; }
        public Nullable<int> noOfPlayers { get; set; }
        public Nullable<int> gameID { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
