//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsoleGame
    {
        public int consoleGameID { get; set; }
        public string title { get; set; }
        public string ESRB { get; set; }
        public string genre { get; set; }
        public string playType { get; set; }
        public Nullable<System.DateTime> releaseDate { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> gameID { get; set; }
        public string consoleID { get; set; }
    
        public virtual Console Console { get; set; }
        public virtual Game Game { get; set; }
    }
}
