//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DandDProfile
    {
        public string dAndDProfileID { get; set; }
        public string characterName { get; set; }
        public string classAndLevel { get; set; }
        public string race { get; set; }
        public string alignment { get; set; }
        public string playerName { get; set; }
        public Nullable<int> gameID { get; set; }
    
        public virtual Game Game { get; set; }
    }
}
